/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Fresaclub } from "./Fresaclub";
export type { IERC20Token } from "./IERC20Token";

export { Fresaclub__factory } from "./factories/Fresaclub__factory";
export { IERC20Token__factory } from "./factories/IERC20Token__factory";
